function f=solve_func(x,M,T,k,dk,ddk,alpha,tao,kphi,kalpha,R,taof,v,miu,Dw,E,I,miua,miut,omega,flambda,qm,rhoi,rhoo,Ai,Ao,g,sign1,sign2)
    dT=x(1);
    dM=x(2);
    Nn=x(3);
    Nb=x(4);
% %去除内外压力及扭矩公式中的2*pi
%     if k~=0
%         f=[dT+k*E*I*dk+sign*miua*sqrt(Nb^2+Nn^2)+flambda-qm*cos(alpha);...
%             k*dM+M*dk-tao*E*I*dk-Nb+miut*Nn-((qm+rhoi*g*Ai-rhoo*g*Ao)*kphi/k*sin(alpha)*sin(alpha));...
%             dM-(miut*R*sqrt(Nb^2+Nn^2)+pi*R^3*omega*(taof/sqrt(v^2+(R*omega)^2)+2*miu/(Dw-2*R)));...
%             E*I*ddk-k*T+Nn+miut*Nb-((qm+rhoi*g*Ai-rhoo*g*Ao)*kalpha/k*sin(alpha))];
%     else
%         f=[dT+k*E*I*dk+sign*miua*sqrt(Nb^2+Nn^2)+flambda-qm*cos(alpha);...
%             k*dM+M*dk-tao*E*I*dk-Nb+miut*Nn;...
%             dM-(miut*R*sqrt(Nb^2+Nn^2)+pi*R^3*omega*(taof/sqrt(v^2+(R*omega)^2)+2*miu/(Dw-2*R)));...
%             E*I*ddk-k*T+Nn+miut*Nb];
%     end
    %去除粘滞阻力影响
    if k~=0
        f=[dT+k*E*I*dk+sign1*miua*sqrt(Nb^2+Nn^2)+sign2*flambda-qm*cos(alpha);...
            k*dM+M*dk-tao*E*I*dk-Nb+miut*Nn-((qm+rhoi*g*Ai-rhoo*g*Ao)*kphi/k*sin(alpha)*sin(alpha));...
            dM-(miut*R*sqrt(Nb^2+Nn^2)+sign2*2*pi*R^3*omega*(taof/sqrt(v^2+(R*omega)^2)+2*miu/(Dw-2*R)));...
            E*I*ddk-k*T+Nn+miut*Nb-((qm+rhoi*g*Ai-rhoo*g*Ao)*kalpha/k*sin(alpha))];
    else
        f=[dT+k*E*I*dk+sign1*miua*sqrt(Nb^2+Nn^2)+sign2*flambda-qm*cos(alpha);...
            k*dM+M*dk-tao*E*I*dk-Nb+miut*Nn;...
            dM-(miut*R*sqrt(Nb^2+Nn^2)+sign2*2*pi*R^3*omega*(taof/sqrt(v^2+(R*omega)^2)+2*miu/(Dw-2*R)));...
            E*I*ddk-k*T+Nn+miut*Nb];
    end