function f=solve_func(x,M,T,k,dk,ddk,alpha,tao,kphi,kalpha,R,r,taof,v1,v2,miu,Dw,E,I,miua,miut,omega,flambdao,qm,rhoi,rhoo,Ai,Ao,g,sign1,sign2,FS,FH,Ft,Nh,Ns)
    dT=x(1);
    dM=x(2);
%     Nn=x(3)+qm*cos(alpha);
    Nn=x(3);
    Nb=x(4);
    if sign1==-1
    if k~=0
        if T>FH
        f=[dT+k*E*I*dk+sign1*(miua)*sqrt(Nb^2+Nn^2)-flambdao-Ft-(qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*cos(alpha);...
%              f=[dT+k*E*I*dk+sign1*(miua)*sqrt(Nn^2)-flambdao-Ft-(qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*cos(alpha);...
            k*dM+M*dk-tao*E*I*dk-Nb+miut*Nn-((qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*kphi/k*sin(alpha)*sin(alpha));...
%             dM+(miut*R*sqrt(Nb^2+Nn^2)+2*pi*R^3*omega*(taof/sqrt(v2^2+(R*omega)^2)+2*miu/(Dw-2*R)))-(miut*r*sqrt(Nb^2+Nn^2)+2*pi*r^3*omega*(taof/sqrt(v1^2+(r*omega)^2)+2*miu/(Dw-2*r)));...
%             dM-miut*R*sqrt(Nb^2+Nn^2);...
            dM+(miut*R*sqrt(Nb^2+Nn^2)+2*pi*R^3*omega*(taof/sqrt(v2^2+(R*omega)^2)+2*miu/(Dw-2*R)));...
            E*I*ddk-k*T+Nn+miut*Nb-((qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*kalpha/k*sin(alpha))];
            
        elseif T<=FH 
            f=[dT+k*E*I*dk+sign1*(miua)*(sqrt(Nb^2+Nn^2)+Nh)-flambdao-Ft-(qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*cos(alpha);...
%                 f=[dT+k*E*I*dk+sign1*(miua)*(sqrt(Nn^2)+Nh)-flambdao-Ft-(qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*cos(alpha);...
            k*dM+M*dk-tao*E*I*dk-Nb+miut*Nn-((qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*kphi/k*sin(alpha)*sin(alpha));...
%             dM+(miut*R*(sqrt(Nb^2+Nn^2)+Nh)+2*pi*R^3*omega*(taof/sqrt(v2^2+(R*omega)^2)+2*miu/(Dw-2*R)))-(miut*r*sqrt(Nb^2+Nn^2)+2*pi*r^3*omega*(taof/sqrt(v1^2+(r*omega)^2)+2*miu/(Dw-2*r)));...
%             dM-miut*R*(sqrt(Nb^2+Nn^2)+Nh);...
            dM+(miut*R*sqrt(Nb^2+Nn^2)+2*pi*R^3*omega*(taof/sqrt(v2^2+(R*omega)^2)+2*miu/(Dw-2*R)));...
            E*I*ddk-k*T+Nn+miut*Nb-((qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*kalpha/k*sin(alpha))];
        end
        
    else
              f=[dT+k*E*I*dk+sign1*(miua)*sqrt(Nb^2+Nn^2)-flambdao-Ft-(qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*cos(alpha);...
%                   f=[dT+k*E*I*dk+sign1*(miua)*sqrt(Nn^2)-flambdao-Ft-(qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*cos(alpha);...
              k*dM+M*dk-tao*E*I*dk-Nb+miut*Nn;...
%               dM-miut*R*sqrt(Nb^2+Nn^2);...
            dM+(miut*R*sqrt(Nb^2+Nn^2)+2*pi*R^3*omega*(taof/sqrt(v2^2+(R*omega)^2)+2*miu/(Dw-2*R)));...
%             dM+(miut*R*sqrt(Nb^2+Nn^2)+2*pi*R^3*omega*(taof/sqrt(v2^2+(R*omega)^2)+2*miu/(Dw-2*R)))-(miut*r*sqrt(Nb^2+Nn^2)+2*pi*r^3*omega*(taof/sqrt(v1^2+(r*omega)^2)+2*miu/(Dw-2*r)));...
              E*I*ddk-k*T+Nn+miut*Nb];           
    end
    else
        if k~=0
        if T>FS
            f=[dT+k*E*I*dk+sign1*(miua)*sqrt(Nb^2+Nn^2)+flambdao-Ft-(qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*cos(alpha);...
%                 f=[dT+k*E*I*dk+sign1*(miua)*sqrt(Nn^2)-flambdao-Ft-(qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*cos(alpha);...
            k*dM+M*dk-tao*E*I*dk-Nb+miut*Nn-((qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*kphi/k*sin(alpha)*sin(alpha));...
%             dM+(miut*R*sqrt(Nb^2+Nn^2)+2*pi*R^3*omega*(taof/sqrt(v2^2+(R*omega)^2)+2*miu/(Dw-2*R)))-(miut*r*sqrt(Nb^2+Nn^2)+2*pi*r^3*omega*(taof/sqrt(v1^2+(r*omega)^2)+2*miu/(Dw-2*r)));...
%             dM-miut*R*sqrt(Nb^2+Nn^2);...
            dM+(miut*R*sqrt(Nb^2+Nn^2)+2*pi*R^3*omega*(taof/sqrt(v2^2+(R*omega)^2)+2*miu/(Dw-2*R)));...
            E*I*ddk-k*T+Nn+miut*Nb-((qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*kalpha/k*sin(alpha))];
        elseif T>FH && T<=FS
        f=[dT+k*E*I*dk+sign1*(miua)*(sqrt(Nb^2+Nn^2)+Ns)+flambdao-Ft-(qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*cos(alpha);...
%             f=[dT+k*E*I*dk+sign1*(miua)*(sqrt(Nn^2)+Ns)+flambdao-Ft-(qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*cos(alpha);...
            k*dM+M*dk-tao*E*I*dk-Nb+miut*Nn-((qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*kphi/k*sin(alpha)*sin(alpha));...
%             dM+(miut*R*(sqrt(Nb^2+Nn^2)+Ns)+2*pi*R^3*omega*(taof/sqrt(v2^2+(R*omega)^2)+2*miu/(Dw-2*R)))-(miut*r*sqrt(Nb^2+Nn^2)+2*pi*r^3*omega*(taof/sqrt(v1^2+(r*omega)^2)+2*miu/(Dw-2*r)));...
%             dM-miut*R*(sqrt(Nb^2+Nn^2)+Ns);...
            dM+(miut*R*sqrt(Nb^2+Nn^2)+2*pi*R^3*omega*(taof/sqrt(v2^2+(R*omega)^2)+2*miu/(Dw-2*R)));...
            E*I*ddk-k*T+Nn+miut*Nb-((qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*kalpha/k*sin(alpha))];
        else 
            f=[dT+k*E*I*dk+sign1*(miua)*(sqrt(Nb^2+Nn^2)+Nh)+flambdao-Ft-(qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*cos(alpha);...
%                  f=[dT+k*E*I*dk+sign1*(miua)*(sqrt(Nn^2)+Nh)+flambdao-Ft-(qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*cos(alpha);...
            k*dM+M*dk-tao*E*I*dk-Nb+miut*Nn-((qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*kphi/k*sin(alpha)*sin(alpha));...
%             dM+(miut*R*(sqrt(Nb^2+Nn^2)+Nh)+2*pi*R^3*omega*(taof/sqrt(v2^2+(R*omega)^2)+2*miu/(Dw-2*R)))-(miut*r*sqrt(Nb^2+Nn^2)+2*pi*r^3*omega*(taof/sqrt(v1^2+(r*omega)^2)+2*miu/(Dw-2*r)));...
%             dM-miut*R*(sqrt(Nb^2+Nn^2)+Nh);...
            dM+(miut*R*sqrt(Nb^2+Nn^2)+2*pi*R^3*omega*(taof/sqrt(v2^2+(R*omega)^2)+2*miu/(Dw-2*R)));...
            E*I*ddk-k*T+Nn+miut*Nb-((qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*kalpha/k*sin(alpha))];
        end
    else
              f=[dT+k*E*I*dk+sign1*(miua)*sqrt(Nb^2+Nn^2)+flambdao-Ft-(qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*cos(alpha);...
%                    f=[dT+k*E*I*dk+sign1*(miua)*sqrt(Nn^2)+flambdao-Ft-(qm+(rhoi*g)*Ai-(rhoo*g)*Ao)*cos(alpha);...
              k*dM+M*dk-tao*E*I*dk-Nb+miut*Nn;...
%               dM-miut*R*sqrt(Nb^2+Nn^2);...
            dM+(miut*R*sqrt(Nb^2+Nn^2)+2*pi*R^3*omega*(taof/sqrt(v2^2+(R*omega)^2)+2*miu/(Dw-2*R)));...
%             dM+(miut*R*sqrt(Nb^2+Nn^2)+2*pi*R^3*omega*(taof/sqrt(v2^2+(R*omega)^2)+2*miu/(Dw-2*R)))-(miut*r*sqrt(Nb^2+Nn^2)+2*pi*r^3*omega*(taof/sqrt(v1^2+(r*omega)^2)+2*miu/(Dw-2*r)));...
              E*I*ddk-k*T+Nn+miut*Nb];           
        end
    end